### ISSUE TITLE
restarting pf hangs

### ISSUE THREAD

**Issue by thallian** [ployground/bsdploy#57]
When configuring the jailhost it hangs indefinitely at the step `jails_host | restart pf`.  
The same thing happens when I ssh into the jailhost and try to restart it manually but after a reboot it seems to be running.
The only line in the log (after enabling pflog) does not indicate a problem: `capability mode sandbox enabled`

This happens for me with the latest bsdploy version while deploying to virtualbox on both Mac OSX and Archlinux.

Did someone ever experience something similar?

**Comment by tomster** [comment]
yes, i'm afraid, i merged @fschulze 's pf branch too soon... or rather without testing it on a fresh installation.

since this essentially breaks bsdploy on master i have reverted the merge of the pf branch and (force) pushed the result to master.

@fschulze we'll need to fix the hang before we can switch to pf.

@thallian if you pull again, you should have a working master again.

also, since apparently people (at least two :-) are actually using bsdploy from git checkout i'll make more of an effort to keep master runnable at all times from now on :-)

**Comment by tomster** [comment]
this has been fixed in 2.0.0
