### ISSUE TITLE
What is the License

### ISSUE THREAD

**Issue by AmitKumarDas** [ployground/bsdploy#99]
Is this an active project ?
Any thoughts regarding License ?

**Comment by tomster** [comment]
hi amit,

thanks for the question - it had totally slipped my mind, that the license was not explicit enough. like the other members of the ploy family, bsdploy is BSD licensed, i've fixed that omission in a commit, just now (fe7bc87)

the project is "semi active" - i.e. @fschulze and i use bsdploy almost daily in our work, but don't get around adding new features, because of said work :) OTOH in its use it has proven to be stable and "good enough".

if you are interested in anything else, feel free to (ab)use this issue for a conversation :)

**Comment by AmitKumarDas** [comment]
Thanks @tomster. This will suffice. 
My team at CloudByte might be interested if its existing product goes for design changes.
